/**
 * Email template catalog — 300+ ready, fully editable templates.
 * 80 core purposes × 3 tones (FORMAL / FRIENDLY / MINIMAL) in English + a Bengali set.
 * Every template supports {{variable}} interpolation; the panel exposes a live editor.
 */

export interface CatalogCore {
  b: string // base key
  n: string // name
  c: string // category
  e: string // event code
  v: string[] // variables
  s: string // EN subject
  m: string // EN message body (plain sentences; \n = paragraph break)
  sb: string // BN subject
  mb: string // BN message
}

export const CATALOG_CORES: CatalogCore[] = [
  // ── PAYMENT (11) ──
  { b: 'payment_received', n: 'Payment received', c: 'PAYMENT', e: 'PAYMENT_SUCCESS', v: ['customer_name', 'amount', 'trx_id', 'brand'], s: 'Payment received — {{amount}} BDT', m: 'We have received your payment of {{amount}} BDT.\nTransaction reference: {{trx_id}}.\nYou can verify this receipt any time from your customer portal.\nThank you for your business.', sb: '{{amount}} টাকা পেমেন্ট গ্রহণ করা হয়েছে', mb: 'আপনার {{amount}} টাকার পেমেন্ট আমরা পেয়েছি।\nলেনদেন রেফারেন্স: {{trx_id}}।\nরসিদ যেকোনো সময় কাস্টমার পোর্টাল থেকে যাচাই করতে পারবেন।\nআপনার ব্যবসার জন্য ধন্যবাদ।' },
  { b: 'payment_failed', n: 'Payment failed', c: 'PAYMENT', e: 'PAYMENT_FAILED', v: ['customer_name', 'amount', 'brand'], s: 'Payment could not be completed', m: 'Your payment of {{amount}} BDT could not be completed.\nNo money has left your account — if it appears deducted it will auto-refund within 3 working days.\nYou can retry the payment from the original link.\nNeed help? Just reply to this email.', sb: 'পেমেন্ট সম্পন্ন হতে পারেনি', mb: 'আপনার {{amount}} টাকার পেমেন্ট সম্পন্ন হতে পারেনি।\nআপনার অ্যাকাউন্ট থেকে টাকা কাটেনি — কাটা হলে ৩ কর্মদিবসের মধ্যে ফেরত আসবে।\nমূল লিংক থেকে আবার চেষ্টা করতে পারেন।\nসাহায্য লাগলে এই ইমেইলের উত্তর দিন।' },
  { b: 'payment_cancelled', n: 'Payment cancelled', c: 'PAYMENT', e: 'PAYMENT_CANCEL', v: ['customer_name', 'amount', 'brand'], s: 'Your payment was cancelled', m: 'You cancelled the payment of {{amount}} BDT.\nIf this was a mistake you can start again using the original payment request.\nWe kept your cart and details for 7 days.', sb: 'আপনার পেমেন্ট বাতিল করা হয়েছে', mb: 'আপনি {{amount}} টাকার পেমেন্ট বাতিল করেছেন।\nভুলবশত হলে মূল পেমেন্ট রিকোয়েস্ট থেকে আবার শুরু করতে পারেন।\nআপনার তথ্য ৭ দিন সংরক্ষিত থাকবে।' },
  { b: 'payment_reminder', n: 'Payment pending reminder', c: 'PAYMENT', e: 'PAYMENT_DUE', v: ['customer_name', 'amount', 'brand'], s: 'Reminder: payment of {{amount}} BDT is pending', m: 'This is a friendly reminder that your payment of {{amount}} BDT is still pending.\nThe payment link stays active for 48 more hours.\nIf you have already paid, please ignore this message.', sb: 'রিমাইন্ডার: {{amount}} টাকার পেমেন্ট এখনো বাকি', mb: 'বন্ধুসুলভ রিমাইন্ডার — আপনার {{amount}} টাকার পেমেন্ট এখনো বাকি আছে।\nপেমেন্ট লিংক আরও ৪৮ ঘণ্টা সক্রিয় থাকবে।\nপরিশোধ করে থাকলে এই বার্তা উপেক্ষা করুন।' },
  { b: 'payment_receipt', n: 'Official receipt', c: 'PAYMENT', e: 'PAYMENT_SUCCESS', v: ['customer_name', 'amount', 'trx_id', 'brand'], s: 'Your receipt from {{brand}}', m: 'This is your official receipt.\nAmount: {{amount}} BDT\nTransaction: {{trx_id}}\nKeep this email for your records or verify it via the QR code on your invoice.', sb: '{{brand}} থেকে আপনার রসিদ', mb: 'এটি আপনার অফিসিয়াল রসিদ।\nপরিমাণ: {{amount}} টাকা\nলেনদেন: {{trx_id}}\nরেকর্ডের জন্য সংরক্ষণ করুন বা ইনভয়েসের QR দিয়ে যাচাই করুন।' },
  { b: 'payment_link_shared', n: 'Payment link shared', c: 'PAYMENT', e: 'PAYMENT_DUE', v: ['customer_name', 'amount', 'brand'], s: 'A payment request for {{amount}} BDT', m: '{{brand}} has requested a payment of {{amount}} BDT from you.\nOpen the secure payment page, choose any method (bKash, Nagad, Rocket, Upay, card) and pay in minutes.\nThe link expires in 7 days.', sb: '{{amount}} টাকার পেমেন্ট রিকোয়েস্ট', mb: '{{brand}} আপনার কাছে {{amount}} টাকার পেমেন্ট রিকোয়েস্ট করেছে।\nসুরক্ষিত পেমেন্ট পেজে গিয়ে bKash, Nagad, Rocket, Upay বা কার্ড — যেকোনো মাধ্যমে মিনিটেই পরিশোধ করুন।\nলিংক ৭ দিনে মেয়াদোত্তীর্ণ হবে।' },
  { b: 'underpayment_notice', n: 'Underpayment notice', c: 'PAYMENT', e: 'PAYMENT_FAILED', v: ['customer_name', 'amount', 'brand'], s: 'Action needed: amount mismatch on your payment', m: 'We received a payment from you but the amount did not match the request.\nSent amounts below the required total cannot be auto-verified.\nPlease complete the remaining amount or contact support for a manual review.', sb: 'প্রয়োজনীয় পদক্ষেপ: পেমেন্টের পরিমাণ অমিল', mb: 'আপনার পেমেন্ট পেয়েছি, কিন্তু পরিমাণ মিলছে না।\nপ্রয়োজনীয় টাকার চেয়ে কম পাঠালে স্বয়ংক্রিয়ভাবে যাচাই হয় না।\nবাকি পরিমাণ সম্পন্ন করুন বা ম্যানুয়াল রিভিউয়ের জন্য সাপোর্টে যোগাযোগ করুন।' },
  { b: 'settlement_statement', n: 'Settlement statement', c: 'PAYMENT', e: 'SETTLEMENT', v: ['period', 'amount', 'brand'], s: 'Settlement statement — {{period}}', m: 'Your settlement for {{period}} is ready.\nNet settled amount: {{amount}} BDT.\nExpected vs actual reconciliation and fee details are attached in your dashboard.', sb: 'সেটেলমেন্ট স্টেটমেন্ট — {{period}}', mb: '{{period}} মাসের আপনার সেটেলমেন্ট প্রস্তুত।\nনিট সেটেল হওয়া পরিমাণ: {{amount}} টাকা।\nপ্রত্যাশিত বনাম প্রাপ্ত মিলকরণ ও ফি-এর বিবরণ ড্যাশবোর্ডে দেখুন।' },
  { b: 'recurring_charged', n: 'Recurring payment charged', c: 'PAYMENT', e: 'SUBSCRIPTION_RENEWED', v: ['customer_name', 'amount', 'plan_name', 'brand'], s: '{{plan_name}} renewed — {{amount}} BDT', m: 'Your {{plan_name}} subscription renewed successfully.\nAmount charged: {{amount}} BDT.\nManage or cancel your plan any time from the customer portal.', sb: '{{plan_name}} নবায়ন হয়েছে — {{amount}} টাকা', mb: 'আপনার {{plan_name}} সাবস্ক্রিপশন সফলভাবে নবায়ন হয়েছে।\nচার্জ করা হয়েছে: {{amount}} টাকা।\nকাস্টমার পোর্টাল থেকে যেকোনো সময় প্ল্যান পরিবর্তন বা বাতিল করুন।' },
  { b: 'payment_verified', n: 'Manual verification approved', c: 'PAYMENT', e: 'PAYMENT_SUCCESS', v: ['customer_name', 'trx_id', 'brand'], s: 'Your payment has been verified', m: 'Good news — our team manually verified your payment.\nTransaction: {{trx_id}} is now marked as complete.\nYour receipt has been updated in the portal.', sb: 'আপনার পেমেন্ট যাচাই সম্পন্ন হয়েছে', mb: 'সুখবর — আমাদের টিম আপনার পেমেন্ট ম্যানুয়ালি যাচাই করেছে।\nলেনদেন {{trx_id}} এখন সম্পন্ন হিসেবে চিহ্নিত।\nপোর্টালে রসিদ আপডেট করা হয়েছে।' },
  { b: 'payment_disputed_hold', n: 'Payment under dispute hold', c: 'PAYMENT', e: 'DISPUTE_OPENED', v: ['customer_name', 'amount', 'brand'], s: 'A payment of {{amount}} BDT is under review', m: 'A dispute has been opened on a payment of {{amount}} BDT.\nFunds are on temporary hold while we review the case.\nBoth parties may submit evidence through the support channel within 14 days.', sb: '{{amount}} টাকার পেমেন্ট পর্যালোচনাধীন', mb: '{{amount}} টাকার একটি পেমেন্টে বিরোধ খোলা হয়েছে।\nমামলা পর্যালোচনার সময় অর্থ সাময়িকভাবে হোল্ডে থাকবে।\n১৪ দিনের মধ্যে দুই পক্ষ সাপোর্ট চ্যানেলে প্রমাণ জমা দিতে পারবে।' },
  // ── INVOICE (9) ──
  { b: 'invoice_created', n: 'Invoice issued', c: 'INVOICE', e: 'INVOICE_CREATED', v: ['customer_name', 'invoice_number', 'amount', 'due_date', 'brand'], s: 'Invoice {{invoice_number}} from {{brand}}', m: 'A new invoice {{invoice_number}} has been issued for you.\nTotal: {{amount}} BDT — due by {{due_date}}.\nPay online from the secure invoice page (bKash, Nagad, Rocket, Upay, card).', sb: '{{brand}} থেকে ইনভয়েস {{invoice_number}}', mb: 'আপনার জন্য নতুন ইনভয়েস {{invoice_number}} ইস্যু হয়েছে।\nমোট: {{amount}} টাকা — শেষ তারিখ {{due_date}}।\nসুরক্ষিত ইনভয়েস পেজ থেকে অনলাইনে পরিশোধ করুন।' },
  { b: 'invoice_due_soon', n: 'Invoice due in 3 days', c: 'INVOICE', e: 'INVOICE_OVERDUE', v: ['customer_name', 'invoice_number', 'amount', 'due_date', 'brand'], s: 'Invoice {{invoice_number}} is due on {{due_date}}', m: 'A quick reminder: invoice {{invoice_number}} ({{amount}} BDT) becomes due on {{due_date}}.\nPay online in under a minute from your invoice link.', sb: 'ইনভয়েস {{invoice_number}} শেষ হবে {{due_date}} তারিখে', mb: 'ছোট্ট রিমাইন্ডার: ইনভয়েস {{invoice_number}} ({{amount}} টাকা) {{due_date}} তারিখে শেষ হবে।\nইনভয়েস লিংক থেকে এক মিনিটেই অনলাইনে পরিশোধ করুন।' },
  { b: 'invoice_overdue', n: 'Invoice overdue', c: 'INVOICE', e: 'INVOICE_OVERDUE', v: ['customer_name', 'invoice_number', 'amount', 'brand'], s: 'Invoice {{invoice_number}} is now overdue', m: 'Invoice {{invoice_number}} for {{amount}} BDT is now past its due date.\nPlease settle it as soon as possible to avoid service interruption.\nIf you already paid, share the transaction ID and we will reconcile instantly.', sb: 'ইনভয়েস {{invoice_number}} মেয়াদোত্তীর্ণ', mb: '{{amount}} টাকার ইনভয়েস {{invoice_number}} মেয়াদ পেরিয়ে গেছে।\nসেবা ব্যাহত না হওয়ার জন্য দ্রুত পরিশোধ করুন।\nইতিমধ্যে পরিশোধ করে থাকলে লেনদেন আইডি জানান, আমরা সাথে সাথে মিলিয়ে নেব।' },
  { b: 'invoice_paid', n: 'Invoice paid — thank you', c: 'INVOICE', e: 'PAYMENT_SUCCESS', v: ['customer_name', 'invoice_number', 'amount', 'brand'], s: 'Invoice {{invoice_number}} paid', m: 'We received {{amount}} BDT for invoice {{invoice_number}}.\nYour account is fully settled — the paid receipt is attached to your portal.', sb: 'ইনভয়েস {{invoice_number}} পরিশোধিত', mb: 'ইনভয়েস {{invoice_number}}-এর {{amount}} টাকা পেয়েছি।\nআপনার হিসাব সম্পূর্ণ পরিশোধিত — পোর্টালে রসিদ যুক্ত করা হয়েছে।' },
  { b: 'invoice_partial', n: 'Partial payment received', c: 'INVOICE', e: 'PAYMENT_SUCCESS', v: ['customer_name', 'invoice_number', 'amount', 'due', 'brand'], s: 'Partial payment received for {{invoice_number}}', m: 'We received {{amount}} BDT towards invoice {{invoice_number}}.\nRemaining balance: {{due}} BDT.\nPay the rest any time from the invoice page.', sb: '{{invoice_number}}-এ আংশিক পেমেন্ট পেয়েছি', mb: 'ইনভয়েস {{invoice_number}}-এ {{amount}} টাকা পেয়েছি।\nবাকি: {{due}} টাকা।\nইনভয়েস পেজ থেকে যেকোনো সময় বাকিটা পরিশোধ করুন।' },
  { b: 'invoice_cancelled', n: 'Invoice cancelled', c: 'INVOICE', e: 'PAYMENT_CANCEL', v: ['customer_name', 'invoice_number', 'brand'], s: 'Invoice {{invoice_number}} cancelled', m: 'Invoice {{invoice_number}} has been cancelled and no payment is due.\nIf you were charged in error, a refund is on the way (3–5 working days).', sb: 'ইনভয়েস {{invoice_number}} বাতিল', mb: 'ইনভয়েস {{invoice_number}} বাতিল করা হয়েছে, কোনো টাকা দিতে হবে না।\nভুলবশত চার্জ হয়ে থাকলে ৩–৫ কর্মদিবসে ফেরত পাবেন।' },
  { b: 'recurring_invoice_scheduled', n: 'Recurring invoice scheduled', c: 'INVOICE', e: 'INVOICE_CREATED', v: ['customer_name', 'amount', 'interval', 'next_date', 'brand'], s: 'Your recurring invoice is set up', m: 'A recurring invoice of {{amount}} BDT ({{interval}}) has been scheduled.\nNext automatic billing: {{next_date}}.\nYou will receive a receipt after every cycle.', sb: 'পুনরাবৃত্ত ইনভয়েস নির্ধারিত হয়েছে', mb: '{{amount}} টাকার ({{interval}}) পুনরাবৃত্ত ইনভয়েস নির্ধারণ করা হয়েছে।\nপরবর্তী স্বয়ংক্রিয় বিলিং: {{next_date}}।\nপ্রতি সাইকেল শেষে রসিদ পাবেন।' },
  { b: 'invoice_reminder_final', n: 'Final invoice notice', c: 'INVOICE', e: 'INVOICE_OVERDUE', v: ['customer_name', 'invoice_number', 'amount', 'brand'], s: 'Final notice: invoice {{invoice_number}}', m: 'This is a final reminder for invoice {{invoice_number}} ({{amount}} BDT).\nAfter 7 days the account may be paused and a late fee may apply per the merchant agreement.\nSettle now or contact us to arrange a plan.', sb: 'চূড়ান্ত নোটিশ: ইনভয়েস {{invoice_number}}', mb: 'ইনভয়েস {{invoice_number}} ({{amount}} টাকা)-এর চূড়ান্ত রিমাইন্ডার।\n৭ দিন পর অ্যাকাউন্ট সাময়িক বন্ধ এবং মার্চেন্ট চুক্তি অনুযায়ী বিলম্ব ফি প্রযোজ্য হতে পারে।\nএখনই পরিশোধ করুন বা কিস্তির ব্যবস্থার জন্য যোগাযোগ করুন।' },
  { b: 'monthly_statement', n: 'Monthly account statement', c: 'INVOICE', e: 'STATEMENT', v: ['customer_name', 'period', 'brand'], s: 'Your statement for {{period}}', m: 'Your statement for {{period}} is ready.\nIt includes all invoices, payments, refunds and outstanding balances.\nDownload the PDF from the customer portal.', sb: '{{period}} মাসের স্টেটমেন্ট', mb: '{{period}} মাসের স্টেটমেন্ট প্রস্তুত।\nএতে সব ইনভয়েস, পেমেন্ট, রিফান্ড ও বাকি ব্যালেন্স রয়েছে।\nকাস্টমার পোর্টাল থেকে PDF ডাউনলোড করুন।' },
  // ── SUBSCRIPTION (10) ──
  { b: 'sub_trial_started', n: 'Trial started', c: 'SUBSCRIPTION', e: 'SUBSCRIPTION_RENEWED', v: ['customer_name', 'plan_name', 'days', 'brand'], s: 'Your {{plan_name}} trial has started', m: 'Welcome aboard! Your {{days}}-day trial of {{plan_name}} is now active.\nNo charge until the trial ends.\nYou can cancel any time — we will remind you 3 days before billing starts.', sb: 'আপনার {{plan_name}} ট্রায়াল শুরু হয়েছে', mb: 'স্বাগতম! {{plan_name}}-এর {{days}} দিনের ট্রায়াল সক্রিয় হয়েছে।\nট্রায়াল শেষ না হওয়া পর্যন্ত কোনো চার্জ নেই।\nযেকোনো সময় বাতিল করতে পারবেন — বিলিং শুরুর ৩ দিন আগে মনে করিয়ে দেব।' },
  { b: 'sub_trial_ending', n: 'Trial ending soon', c: 'SUBSCRIPTION', e: 'SUBSCRIPTION_RENEWED', v: ['customer_name', 'plan_name', 'days', 'amount', 'brand'], s: 'Your trial ends in {{days}} days', m: 'Your {{plan_name}} trial ends in {{days}} days.\nAfter that it renews at {{amount}} BDT per cycle.\nDo nothing to continue, or cancel before the trial ends to avoid charges.', sb: '{{days}} দিনে আপনার ট্রায়াল শেষ হবে', mb: '{{plan_name}} ট্রায়াল {{days}} দিনের মধ্যে শেষ হবে।\nএরপর প্রতি সাইকেলে {{amount}} টাকায় নবায়ন হবে।\nচালিয়ে যেতে কিছু করতে হবে না, বা ট্রায়ালের মধ্যে বাতিল করে চার্জ এড়াতে পারেন।' },
  { b: 'sub_renewal_success', n: 'Renewal successful', c: 'SUBSCRIPTION', e: 'SUBSCRIPTION_RENEWED', v: ['customer_name', 'plan_name', 'amount', 'brand'], s: '{{plan_name}} renewed successfully', m: 'Your {{plan_name}} subscription renewed for {{amount}} BDT.\nNext billing is one full cycle away.\nInvoice and receipt are available in the portal.', sb: '{{plan_name}} সফলভাবে নবায়নিত', mb: 'আপনার {{plan_name}} সাবস্ক্রিপশন {{amount}} টাকায় নবায়ন হয়েছে।\nপরবর্তী বিলিং এক পূর্ণ সাইকেল দূরে।\nইনভয়েস ও রসিদ পোর্টালে পাওয়া যাবে।' },
  { b: 'sub_renewal_failed', n: 'Renewal failed', c: 'SUBSCRIPTION', e: 'PAYMENT_FAILED', v: ['customer_name', 'plan_name', 'amount', 'brand'], s: 'Renewal failed for {{plan_name}}', m: 'We could not charge {{amount}} BDT for your {{plan_name}} plan.\nWe will retry automatically — no action needed unless this email repeats.\nUpdate your payment method from the portal to fix it instantly.', sb: '{{plan_name}}-এর নবায়ন ব্যর্থ হয়েছে', mb: 'আপনার {{plan_name}} প্ল্যানের {{amount}} টাকা চার্জ করা যায়নি।\nআমরা স্বয়ংক্রিয়ভাবে আবার চেষ্টা করব — এই ইমেইল বারবার না এলে কিছু করতে হবে না।\nপোর্টাল থেকে পেমেন্ট মাধ্যম আপডেট করলে সাথে সাথেই সমাধান হবে।' },
  { b: 'sub_dunning_1', n: 'Dunning reminder 1', c: 'SUBSCRIPTION', e: 'PAYMENT_FAILED', v: ['customer_name', 'plan_name', 'amount', 'brand'], s: 'Action needed: update your payment method', m: 'Your {{plan_name}} renewal of {{amount}} BDT failed on the first attempt.\nYour service continues for now — grace period is 3 days.\nUpdate your payment details to avoid interruption.', sb: 'প্রয়োজনীয় পদক্ষেপ: পেমেন্ট মাধ্যম আপডেট করুন', mb: '{{plan_name}}-এর {{amount}} টাকা নবায়ন প্রথম চেষ্টাতেই ব্যর্থ হয়েছে।\nএখনো সেবা চালু আছে — গ্রেস পিরিয়ড ৩ দিন।\nসেবা বন্ধ এড়াতে পেমেন্ট তথ্য আপডেট করুন।' },
  { b: 'sub_dunning_2', n: 'Dunning reminder 2', c: 'SUBSCRIPTION', e: 'PAYMENT_FAILED', v: ['customer_name', 'plan_name', 'amount', 'brand'], s: 'Second attempt failed — {{plan_name}}', m: 'The second automatic retry for {{plan_name}} ({{amount}} BDT) also failed.\nOne final retry happens in 24 hours, then the plan pauses.\nFix your payment method now to keep everything running.', sb: 'দ্বিতীয় চেষ্টাও ব্যর্থ — {{plan_name}}', mb: '{{plan_name}} ({{amount}} টাকা)-এর দ্বিতীয় স্বয়ংক্রিয় চেষ্টাও ব্যর্থ।\n২৪ ঘণ্টা পর শেষ চেষ্টা হবে, এরপর প্ল্যান সাময়িক বন্ধ হবে।\nসব চালু রাখতে এখনই পেমেন্ট মাধ্যম ঠিক করুন।' },
  { b: 'sub_dunning_final', n: 'Dunning final notice', c: 'SUBSCRIPTION', e: 'PAYMENT_FAILED', v: ['customer_name', 'plan_name', 'brand'], s: 'Your {{plan_name}} plan is paused', m: 'After all retries, your {{plan_name}} subscription is now paused.\nYour data is safe for 30 days.\nRe-activate any time from the portal — everything resumes instantly.', sb: 'আপনার {{plan_name}} প্ল্যান বিরত আছে', mb: 'সব চেষ্টা ব্যর্থ হওয়ায় {{plan_name}} সাবস্ক্রিপশন এখন বিরত আছে।\nআপনার ডেটা ৩০ দিন নিরাপদ থাকবে।\nপোর্টাল থেকে যেকোনো সময় পুনরায় সক্রিয় করুন — সব সাথে সাথে ফিরে আসবে।' },
  { b: 'sub_cancelled', n: 'Subscription cancelled', c: 'SUBSCRIPTION', e: 'PAYMENT_CANCEL', v: ['customer_name', 'plan_name', 'brand'], s: '{{plan_name}} cancelled', m: 'Your {{plan_name}} subscription has been cancelled as requested.\nIt stays active until the end of the paid period.\nChanged your mind? One click in the portal re-activates it.', sb: '{{plan_name}} বাতিল হয়েছে', mb: 'আপনার অনুরোধে {{plan_name}} সাবস্ক্রিপশন বাতিল হয়েছে।\nপ্রদত্ত সময় শেষ পর্যন্ত এটি সক্রিয় থাকবে।\nমন বদলেছে? পোর্টালে এক ক্লিকেই আবার চালু হবে।' },
  { b: 'sub_upgraded', n: 'Plan upgraded', c: 'SUBSCRIPTION', e: 'SUBSCRIPTION_RENEWED', v: ['customer_name', 'plan_name', 'amount', 'brand'], s: 'Welcome to {{plan_name}}', m: 'Your upgrade to {{plan_name}} is complete.\nNew features are unlocked right away and the prorated charge of {{amount}} BDT was applied.', sb: '{{plan_name}}-এ স্বাগতম', mb: '{{plan_name}}-এ আপনার আপগ্রেড সম্পন্ন।\nনতুন ফিচার এখনই আনলক হয়েছে এবং হিসাবঅনুযায়ী {{amount}} টাকা চার্জ হয়েছে।' },
  { b: 'sub_downgraded', n: 'Plan downgraded', c: 'SUBSCRIPTION', e: 'PAYMENT_CANCEL', v: ['customer_name', 'plan_name', 'brand'], s: 'Plan changed to {{plan_name}}', m: 'Your plan will switch to {{plan_name}} at the end of the current cycle.\nNo refunds are due; credit for unused time stays on your account.', sb: 'প্ল্যান {{plan_name}}-এ পরিবর্তন', mb: 'বর্তমান সাইকেল শেষে আপনার প্ল্যান {{plan_name}}-এ বদলে যাবে।\nকোনো ফেরত বাকি নেই; অব্যবহৃত সময়ের ক্রেডিট অ্যাকাউন্টে জমা থাকবে।' },
  // ── SECURITY (12) ──
  { b: 'sec_welcome', n: 'Welcome email', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'brand'], s: 'Welcome to {{brand}}', m: 'Your account is ready.\nSign in, enable two-factor authentication and explore your dashboard.\nOur beginners guide walks you through the first payment in under 5 minutes.', sb: '{{brand}}-এ স্বাগতম', mb: 'আপনার অ্যাকাউন্ট প্রস্তুত।\nসাইন ইন করে টু-ফ্যাক্টর চালু করুন এবং ড্যাশবোর্ড ঘুরে দেখুন।\nবিগিনার গাইড ৫ মিনিটেই প্রথম পেমেন্ট সেটআপ শেখাবে।' },
  { b: 'sec_verify_email', n: 'Verify email address', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'code', 'brand'], s: 'Verify your email — code {{code}}', m: 'Use this code to verify your email address: {{code}}\nThe code expires in 10 minutes.\nNever share this code with anyone — our team will never ask for it.', sb: 'ইমেইল যাচাই করুন — কোড {{code}}', mb: 'ইমেইল যাচাইয়ের কোড: {{code}}\nকোডটি ১০ মিনিটে মেয়াদোত্তীর্ণ হবে।\nকাউকে কোড দেবেন না — আমাদের টিম কখনো চাইবে না।' },
  { b: 'sec_password_reset', n: 'Password reset', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'code', 'brand'], s: 'Reset your password', m: 'A password reset was requested for your account.\nReset code: {{code}} (valid 15 minutes).\nIf this was not you, ignore this email — your password stays unchanged.', sb: 'পাসওয়ার্ড রিসেট করুন', mb: 'আপনার অ্যাকাউন্টে পাসওয়ার্ড রিসেটের অনুরোধ করা হয়েছে।\nরিসেট কোড: {{code}} (১৫ মিনিট বৈধ)।\nআপনি না করে থাকলে এই ইমেইল উপেক্ষা করুন — পাসওয়ার্ড অপরিবর্তিত থাকবে।' },
  { b: 'sec_password_changed', n: 'Password changed', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'time', 'device', 'brand'], s: 'Your password was changed', m: 'Your password was changed on {{time}} from {{device}}.\nNot you? Reset your password immediately and review active sessions in Security Center.', sb: 'আপনার পাসওয়ার্ড পরিবর্তন হয়েছে', mb: '{{time}}-এ {{device}} থেকে আপনার পাসওয়ার্ড পরিবর্তন হয়েছে।\nআপনি না হলে সাথে সাথে পাসওয়ার্ড রিসেট করুন এবং সিকিউরিটি সেন্টারে সেশন দেখুন।' },
  { b: 'sec_login_new_device', n: 'New device sign-in', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'device', 'time', 'brand'], s: 'New sign-in from {{device}}', m: 'A new device signed in to your account on {{time}}.\nDevice: {{device}}.\nNot you? Revoke the session from Security Center and rotate your password.', sb: '{{device}} থেকে নতুন লগইন', mb: '{{time}}-এ নতুন একটি ডিভাইস আপনার অ্যাকাউন্টে লগইন করেছে।\nডিভাইস: {{device}}।\nআপনি না হলে সিকিউরিটি সেন্টার থেকে সেশন বাতিল করুন।' },
  { b: 'sec_2fa_enabled', n: '2FA enabled', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'brand'], s: 'Two-factor authentication enabled', m: 'Great move — 2FA now protects your account.\nEach sign-in will need a code from your authenticator app.\nStore your backup codes somewhere safe.', sb: 'টু-ফ্যাক্টর প্রমাণীকরণ চালু হয়েছে', mb: 'দারুণ সিদ্ধান্ত — এখন থেকে 2FA আপনার অ্যাকাউন্ট রক্ষা করবে।\nপ্রতিটি লগইনে অথেনটিকেটর অ্যাপের কোড লাগবে।\nব্যাকআপ কোড নিরাপদে রাখুন।' },
  { b: 'sec_2fa_disabled', n: '2FA disabled — action needed', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'brand'], s: 'Two-factor authentication was disabled', m: '2FA was turned off on your account.\nIf this was not you, secure your account immediately: reset password, review sessions, contact support.', sb: 'টু-ফ্যাক্টর প্রমাণীকরণ বন্ধ হয়েছে', mb: 'আপনার অ্যাকাউন্ট থেকে 2FA বন্ধ করা হয়েছে।\nআপনি না হলে সাথে সাথে নিরাপদ করুন: পাসওয়ার্ড রিসেট, সেশন রিভিউ, সাপোর্টে যোগাযোগ।' },
  { b: 'sec_passkey_added', n: 'Passkey added', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'brand'], s: 'A passkey was added to your account', m: 'You can now sign in with your fingerprint, face or device PIN.\nPasskeys are phishing-resistant and faster than passwords.', sb: 'আপনার অ্যাকাউন্টে পাসকি যোগ হয়েছে', mb: 'এখন আঙুলের ছাপ, মুখ বা ডিভাইস পিন দিয়ে লগইন করতে পারবেন।\nপাসকি ফিশিং-প্রতিরোধী এবং পাসওয়ার্ডের চেয়ে দ্রুত।' },
  { b: 'sec_suspicious_login', n: 'Suspicious activity alert', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'device', 'location', 'brand'], s: 'Suspicious sign-in blocked', m: 'We blocked a sign-in attempt that did not look like you.\nDevice: {{device}} — Location: {{location}}.\nReview Security Center and consider rotating your API keys.', sb: 'সন্দেহজনক লগইন প্রতিরোধ করা হয়েছে', mb: 'আপনার নন এমন একটি লগইন প্রচেষ্টা বন্ধ করা হয়েছে।\nডিভাইস: {{device}} — অবস্থান: {{location}}।\nসিকিউরিটি সেন্টার দেখুন এবং API কী রোটেট করার কথা ভাবুন।' },
  { b: 'sec_account_locked', n: 'Account locked', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'reason', 'brand'], s: 'Your account has been locked', m: 'Your account was temporarily locked: {{reason}}.\nContact support to restore access.\nAll active sessions were signed out for safety.', sb: 'আপনার অ্যাকাউন্ট লক করা হয়েছে', mb: 'কারণ: {{reason}} — অ্যাকাউন্ট সাময়িকভাবে লক হয়েছে।\nঅ্যাক্সেস ফেরাতে সাপোর্টে যোগাযোগ করুন।\nনিরাপত্তার জন্য সব সেশন লগ আউট করা হয়েছে।' },
  { b: 'sec_session_revoked', n: 'Session revoked', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'device', 'brand'], s: 'A session was signed out', m: 'Session on {{device}} was signed out remotely.\nIf this was not you, rotate your password now.', sb: 'একটি সেশন লগ আউট করা হয়েছে', mb: '{{device}}-এর সেশন দূর থেকে লগ আউট করা হয়েছে।\nআপনি না হলে এখনই পাসওয়ার্ড রোটেট করুন।' },
  { b: 'sec_api_key_rotated', n: 'API key rotated', c: 'SECURITY', e: 'ACCOUNT', v: ['customer_name', 'name', 'brand'], s: 'API key "{{name}}" was rotated', m: 'A new secret was generated for API key "{{name}}".\nThe old key remains valid for 24 hours only.\nUpdate your integrations before the deadline.', sb: 'API কী "{{name}}" রোটেট হয়েছে', mb: 'API কী "{{name}}"-এর জন্য নতুন সিক্রেট তৈরি হয়েছে।\nপুরোনো কী মাত্র ২৪ ঘণ্টা বৈধ থাকবে।\nসময়ের মধ্যে ইন্টিগ্রেশন আপডেট করুন।' },
  // ── KYC / COMPLIANCE (6) ──
  { b: 'kyc_submitted', n: 'KYC submitted', c: 'KYC', e: 'KYC', v: ['customer_name', 'brand'], s: 'We received your verification documents', m: 'Your KYC documents were submitted successfully.\nReview usually takes 1–2 working days.\nWe will email you the moment the status changes.', sb: 'আপনার যাচাইকরণ ডকুমেন্ট পেয়েছি', mb: 'আপনার KYC ডকুমেন্ট সফলভাবে জমা হয়েছে।\nরিভিউ সাধারণত ১–২ কর্মদিবস সময় নেয়।\nস্টেটাস বদলালেই ইমেইল পাবেন।' },
  { b: 'kyc_approved', n: 'KYC approved', c: 'KYC', e: 'KYC', v: ['customer_name', 'brand'], s: 'Verification approved', m: 'Your identity/business verification is complete.\nAll features, including higher limits and payouts, are now unlocked.', sb: 'যাচাইকরণ অনুমোদিত', mb: 'আপনার পরিচয়/ব্যবসা যাচাইকরণ সম্পন্ন হয়েছে।\nউচ্চ লিমিট ও পেআউটসহ সব ফিচার এখন আনলকড।' },
  { b: 'kyc_rejected', n: 'KYC needs attention', c: 'KYC', e: 'KYC', v: ['customer_name', 'reason', 'brand'], s: 'Verification documents need attention', m: 'We could not verify your documents: {{reason}}.\nPlease resubmit clear, valid copies from the verification page.\nCommon fixes: full document visible, valid until date, matching name.', sb: 'যাচাইকরণ ডকুমেন্টে সমস্যা', mb: 'ডকুমেন্ট যাচাই সম্ভব হয়নি: {{reason}}।\nযাচাইকরণ পেজ থেকে পরিষ্কার, বৈধ কপি আবার জমা দিন।\nসাধারণ সমাধান: পুরো ডকুমেন্ট দৃশ্যমান, মেয়াদ বৈধ, নাম মিলছে।' },
  { b: 'kyc_expiring', n: 'KYC expiring soon', c: 'KYC', e: 'KYC', v: ['customer_name', 'days', 'brand'], s: 'Your verification expires in {{days}} days', m: 'Regulatory rules require re-verification periodically.\nYour current verification expires in {{days}} days.\nRenew now to keep payouts and limits uninterrupted.', sb: '{{days}} দিনে আপনার যাচাইকরণের মেয়াদ শেষ', mb: 'বিধি অনুযায়ী নিয়মিত পুনঃযাচাই প্রয়োজন।\nআপনার বর্তমান যাচাইকরণ {{days}} দিনে শেষ হবে।\nপেআউট ও লিমিট অটুট রাখতে এখনই নবায়ন করুন।' },
  { b: 'kyc_docs_required', n: 'Additional documents required', c: 'KYC', e: 'KYC', v: ['customer_name', 'docs', 'brand'], s: 'Additional documents needed', m: 'To complete verification we need: {{docs}}.\nUpload them from the verification page — encrypted and visible only to our compliance team.', sb: 'অতিরিক্ত ডকুমেন্ট প্রয়োজন', mb: 'যাচাইকরণ সম্পন্ন করতে দরকার: {{docs}}।\nযাচাইকরণ পেজ থেকে আপলোড করুন — এনক্রিপ্টেড, শুধু কমপ্লায়েন্স টিম দেখতে পারে।' },
  { b: 'aml_flag_notice', n: 'Transaction under AML review', c: 'KYC', e: 'COMPLIANCE', v: ['customer_name', 'trx_id', 'brand'], s: 'Transaction {{trx_id}} under standard review', m: 'Transaction {{trx_id}} is undergoing a standard anti-money-laundering review.\nFunds may be held up to 3 working days.\nWe may request supporting documents — this protects your account too.', sb: 'লেনদেন {{trx_id}} স্ট্যান্ডার্ড রিভিউতে', mb: 'লেনদেন {{trx_id}} স্ট্যান্ডার্ড অ্যান্টি-মানি-লন্ডারিং রিভিউতে আছে।\nঅর্থ ৩ কর্মদিবস পর্যন্ত হোল্ড থাকতে পারে।\nপ্রয়োজনে সহায়ক ডকুমেন্ট চাওয়া হতে পারে — এটি আপনার অ্যাকাউন্টও রক্ষা করে।' },
  // ── REFUND / DISPUTE (5) ──
  { b: 'refund_requested', n: 'Refund request received', c: 'REFUND', e: 'REFUND', v: ['customer_name', 'amount', 'trx_id', 'brand'], s: 'Refund request received for {{amount}} BDT', m: 'We received your refund request for transaction {{trx_id}} ({{amount}} BDT).\nTypical processing: 3–5 working days after approval.\nTrack progress in the customer portal.', sb: '{{amount}} টাকার রিফান্ড রিকোয়েস্ট পেয়েছি', mb: '{{trx_id}} লেনদেনের ({{amount}} টাকা) রিফান্ড রিকোয়েস্ট পেয়েছি।\nঅনুমোদনের পর সাধারণত ৩–৫ কর্মদিবস লাগে।\nকাস্টমার পোর্টালে অগ্রগতি দেখুন।' },
  { b: 'refund_processed', n: 'Refund processed', c: 'REFUND', e: 'REFUND', v: ['customer_name', 'amount', 'trx_id', 'brand'], s: 'Refund of {{amount}} BDT processed', m: 'Your refund of {{amount}} BDT for {{trx_id}} has been processed.\nDepending on your bank or MFS provider it lands within 1–5 working days.', sb: '{{amount}} টাকার রিফান্ড প্রক্রিয়াকৃত', mb: '{{trx_id}}-এর {{amount}} টাকার রিফান্ড প্রক্রিয়া করা হয়েছে।\nব্যাংক বা MFS অনুযায়ী ১–৫ কর্মদিবসে পৌঁছাবে।' },
  { b: 'refund_rejected', n: 'Refund declined', c: 'REFUND', e: 'REFUND', v: ['customer_name', 'reason', 'brand'], s: 'Your refund request was declined', m: 'After review we could not approve your refund: {{reason}}.\nYou may appeal within 7 days with new evidence through support.', sb: 'আপনার রিফান্ড রিকোয়েস্ট বাতিল', mb: 'রিভিউয়ের পর রিফান্ড অনুমোদন করা যায়নি: {{reason}}।\n৭ দিনের মধ্যে নতুন প্রমাণসহ সাপোর্টে আপিল করতে পারেন।' },
  { b: 'dispute_opened', n: 'Dispute opened', c: 'REFUND', e: 'DISPUTE_OPENED', v: ['customer_name', 'amount', 'deadline', 'brand'], s: 'Dispute opened on your transaction', m: 'A dispute of {{amount}} BDT was opened.\nSubmit your evidence before {{deadline}}.\nUnhandled disputes may result in a chargeback on your account.', sb: 'লেনদেনে বিরোধ খোলা হয়েছে', mb: '{{amount}} টাকার একটি বিরোধ খোলা হয়েছে।\n{{deadline}}-এর মধ্যে প্রমাণ জমা দিন।\nমামলা না দেখা হলে অ্যাকাউন্টে চার্জব্যাক আসতে পারে।' },
  { b: 'dispute_resolved', n: 'Dispute resolved', c: 'REFUND', e: 'DISPUTE', v: ['customer_name', 'outcome', 'brand'], s: 'Dispute resolved — {{outcome}}', m: 'The dispute on your account is now closed with outcome: {{outcome}}.\nFull details and evidence trail are in the dispute center.', sb: 'বিরোধ নিষ্পত্তি — {{outcome}}', mb: 'আপনার অ্যাকাউন্টের বিরোধ নিষ্পত্তি হয়েছে: {{outcome}}।\nসম্পূর্ণ বিবরণ ও প্রমাণের ধারা ডিসপিউট সেন্টারে আছে।' },
  // ── SUPPORT (4) ──
  { b: 'sup_ticket_received', n: 'Support ticket received', c: 'SUPPORT', e: 'SUPPORT', v: ['customer_name', 'ticket_id', 'brand'], s: 'We received your request — {{ticket_id}}', m: 'Thanks for reaching out. Your ticket {{ticket_id}} is in the queue.\nFirst response usually lands within a few hours.\nReply to this email to add details any time.', sb: 'আপনার রিকোয়েস্ট পেয়েছি — {{ticket_id}}', mb: 'যোগাযোগের জন্য ধন্যবাদ। টিকেট {{ticket_id}} কিউতে আছে।\nপ্রথম উত্তর সাধারণত কয়েক ঘণ্টার মধ্যে আসে।\nবিস্তারিত যোগ করতে এই ইমেইলের উত্তর দিন।' },
  { b: 'sup_reply_received', n: 'New reply on your ticket', c: 'SUPPORT', e: 'SUPPORT', v: ['customer_name', 'ticket_id', 'brand'], s: 'New reply — ticket {{ticket_id}}', m: 'Our team replied to your ticket {{ticket_id}}.\nOpen the portal or reply here to continue the conversation.', sb: 'নতুন উত্তর — টিকেট {{ticket_id}}', mb: 'আমাদের টিম টিকেট {{ticket_id}}-এ উত্তর দিয়েছে।\nপোর্টাল খুলুন বা এখানে উত্তর দিয়ে কথা চালিয়ে যান।' },
  { b: 'sup_ticket_resolved', n: 'Ticket resolved', c: 'SUPPORT', e: 'SUPPORT', v: ['customer_name', 'ticket_id', 'brand'], s: 'Resolved — ticket {{ticket_id}}', m: 'Your ticket {{ticket_id}} is marked resolved.\nNot fully fixed? Reply within 7 days to reopen it.', sb: 'সমাধান — টিকেট {{ticket_id}}', mb: 'টিকেট {{ticket_id}} সমাধান হিসেবে চিহ্নিত হয়েছে।\nসম্পূর্ণ ঠিক হয়নি? ৭ দিনের মধ্যে উত্তর দিলেই আবার খুলে যাবে।' },
  { b: 'sup_feedback', n: 'How did we do?', c: 'SUPPORT', e: 'SUPPORT', v: ['customer_name', 'brand'], s: 'Quick feedback about your support experience', m: 'Was your issue handled well?\nOne-line replies help us improve — no forms, no login.', sb: 'আমাদের সেবা কেমন লাগল?', mb: 'সমস্যা ভালোভাবে সমাধান হয়েছিল?\nএক লাইনের উত্তরই আমাদের উন্নতিতে সাহায্য করবে — ফর্ম বা লগইন লাগবে না।' },
  // ── MARKETING (7) ──
  { b: 'mkt_product_update', n: 'Product update', c: 'MARKETING', e: 'MARKETING', v: ['customer_name', 'updates', 'brand'], s: 'What is new at {{brand}}', m: 'Fresh updates just shipped:\n{{updates}}\nEvery feature is live for you right now.', sb: '{{brand}}-এ নতুন কী আছে', mb: 'এইমাত্র নতুন আপডেট এসেছে:\n{{updates}}\nসব ফিচার এখনই আপনার জন্য সক্রিয়।' },
  { b: 'mkt_newsletter', n: 'Monthly newsletter', c: 'MARKETING', e: 'MARKETING', v: ['customer_name', 'month', 'brand'], s: '{{brand}} digest — {{month}}', m: 'Your monthly digest is here: growth tips, feature spotlights and real merchant stories.\nFive minutes that make your payments smarter.', sb: '{{brand}} ডাইজেস্ট — {{month}}', mb: 'মাসিক ডাইজেস্ট: গ্রোথ টিপস, ফিচার স্পটলাইট ও বাস্তব মার্চেন্ট গল্প।\nপাঁচ মিনিটে আপনার পেমেন্ট আরও স্মার্ট।' },
  { b: 'mkt_promo', n: 'Special offer', c: 'MARKETING', e: 'MARKETING', v: ['customer_name', 'offer', 'expiry', 'brand'], s: 'A special offer for you, {{customer_name}}', m: 'Limited-time: {{offer}}\nValid until {{expiry}}.\nUse it from your dashboard — no code needed.', sb: 'আপনার জন্য বিশেষ অফার', mb: 'সীমিত সময়ের জন্য: {{offer}}\nবৈধ সময়: {{expiry}} পর্যন্ত।\nড্যাশবোর্ড থেকেই ব্যবহার করুন — কোড লাগবে না।' },
  { b: 'mkt_reengage', n: 'We miss you', c: 'MARKETING', e: 'MARKETING', v: ['customer_name', 'brand'], s: 'It has been a while, {{customer_name}}', m: 'Your account is safe and waiting.\nNew automations and smarter gateways landed since your last visit.\nSign in and pick up right where you left off.', sb: 'অনেকদিন দেখা হয়নি, {{customer_name}}', mb: 'আপনার অ্যাকাউন্ট নিরাপদে অপেক্ষা করছে।\nশেষ ভিজিটের পর নতুন অটোমেশন ও স্মার্ট গেটওয়ে এসেছে।\nসাইন ইন করে যেখানে ছেড়েছিলেন সেখান থেকেই শুরু করুন।' },
  { b: 'mkt_birthday', n: 'Birthday wishes', c: 'MARKETING', e: 'MARKETING', v: ['customer_name', 'brand'], s: 'Happy birthday, {{customer_name}}!', m: 'Wishing you a wonderful year ahead.\nA little birthday credit is waiting in your account.', sb: 'শুভ জন্মদিন, {{customer_name}}!', mb: 'সামনের বছরটি অসাধারণ হোক।\nছোট্ট একটি জন্মদিনের ক্রেডিট আপনার অ্যাকাউন্টে অপেক্ষা করছে।' },
  { b: 'mkt_festival', n: 'Festival greetings', c: 'MARKETING', e: 'MARKETING', v: ['customer_name', 'festival', 'brand'], s: 'Warm wishes for {{festival}}', m: 'May this {{festival}} bring joy and prosperity to you and your family.\nFrom all of us at {{brand}}.', sb: '{{festival}}-এর আন্তরিক শুভেচ্ছা', mb: 'এই {{festival}} আপনার ও পরিবারের জীবনে আনন্দ ও সমৃদ্ধি নিয়ে আসুক।\n{{brand}} পরিবারের পক্ষ থেকে।' },
  { b: 'mkt_webinar', n: 'Live event invitation', c: 'MARKETING', e: 'MARKETING', v: ['customer_name', 'event', 'date', 'brand'], s: 'You are invited: {{event}}', m: 'Join us on {{date}} for {{event}} — live walkthrough, Q&A and practical setup tips.\nSeats are limited; save yours from the link.', sb: 'আপনি আমন্ত্রিত: {{event}}', mb: '{{date}} তারিখে {{event}}-এ যোগ দিন — লাইভ ডেমো, প্রশ্নোত্তর ও ব্যবহারিক সেটআপ টিপস।\nআসন সীমিত; লিংক থেকে জায়গা নিশ্চিত করুন।' },
  // ── SYSTEM / ADMIN (12) ──
  { b: 'sys_webhook_failed', n: 'Webhook failing', c: 'SYSTEM', e: 'SYSTEM', v: ['endpoint', 'error', 'brand'], s: 'Webhook failing: {{endpoint}}', m: 'Deliveries to {{endpoint}} are failing: {{error}}\nWe retry with exponential backoff, but persistent failures stop delivery.\nCheck your endpoint or use webhook replay from the developer console.', sb: 'ওয়েবহুক ব্যর্থ হচ্ছে: {{endpoint}}', mb: '{{endpoint}}-এ ডেলিভারি ব্যর্থ হচ্ছে: {{error}}\nআমরা ব্যাকঅফ নিয়ে চেষ্টা চালিয়ে যাচ্ছি, তবে দীর্ঘ ব্যর্থতায় ডেলিভারি বন্ধ হয়।\nএন্ডপয়েন্ট দেখুন বা ডেভেলপার কনসোল থেকে রিপ্লে করুন।' },
  { b: 'sys_provider_failover', n: 'Provider failover used', c: 'SYSTEM', e: 'SYSTEM', v: ['provider', 'next', 'brand'], s: 'Email provider issue — failover engaged', m: '{{provider}} failed a health check, so we routed through {{next}} automatically.\nNo messages were lost.\nReview provider settings when convenient.', sb: 'ইমেইল প্রোভাইডার সমস্যা — ফেইলওভার চালু', mb: '{{provider}} হেলথ চেকে ব্যর্থ হওয়ায় স্বয়ংক্রিয়ভাবে {{next}} দিয়ে পাঠানো হয়েছে।\nকোনো বার্তা হারায়নি।\nসুবিধামতো সময়ে প্রোভাইডার সেটিংস দেখে নিন।' },
  { b: 'sys_export_ready', n: 'Export ready', c: 'SYSTEM', e: 'SYSTEM', v: ['type', 'rows', 'brand'], s: 'Your {{type}} export is ready', m: 'Export of {{rows}} rows is ready to download from the reports page.\nLinks expire in 24 hours.', sb: 'আপনার {{type}} এক্সপোর্ট প্রস্তুত', mb: '{{rows}} সারির এক্সপোর্ট রিপোর্টস পেজ থেকে ডাউনলোডের জন্য প্রস্তুত।\nলিংক ২৪ ঘণ্টায় মেয়াদোত্তীর্ণ হবে।' },
  { b: 'sys_import_done', n: 'Import completed', c: 'SYSTEM', e: 'SYSTEM', v: ['type', 'done', 'failed', 'brand'], s: 'Import finished: {{done}} ok, {{failed}} failed', m: 'Your {{type}} import finished.\nSuccessfully imported: {{done}}. Failed rows: {{failed}} (see the import log for reasons).', sb: 'ইমপোর্ট সম্পন্ন: {{done}} সফল, {{failed}} ব্যর্থ', mb: 'আপনার {{type}} ইমপোর্ট শেষ।\nসফল: {{done}}। ব্যর্থ সারি: {{failed}} (কারণ ইমপোর্ট লগে দেখুন)।' },
  { b: 'sys_automation_failed', n: 'Automation run failed', c: 'SYSTEM', e: 'SYSTEM', v: ['name', 'error', 'brand'], s: 'Automation "{{name}}" hit an error', m: 'Automation {{name}} failed with: {{error}}\nOpen the automations page to view the run log and retry.', sb: 'অটোমেশন "{{name}}" সমস্যায় পড়েছে', mb: 'অটোমেশন {{name}} ব্যর্থ: {{error}}\nঅটোমেশন পেজ থেকে রান লগ দেখুন ও আবার চালান।' },
  { b: 'sys_daily_summary', n: 'Daily summary', c: 'SYSTEM', e: 'DIGEST', v: ['today_amount', 'today_count', 'pending', 'brand'], s: 'Today at a glance — {{today_amount}} BDT collected', m: 'Collections today: {{today_amount}} BDT across {{today_count}} payments.\nPending checkouts: {{pending}}.\nEverything else looks healthy.', sb: 'আজকের সারসংক্ষেপ — {{today_amount}} টাকা সংগ্রহ', mb: 'আজকের সংগ্রহ: {{today_count}} পেমেন্টে {{today_amount}} টাকা।\nঅপেক্ষমাণ চেকআউট: {{pending}}।\nবাকি সব স্বাভাবিক আছে।' },
  { b: 'sys_weekly_summary', n: 'Weekly summary', c: 'SYSTEM', e: 'DIGEST', v: ['week_amount', 'week_count', 'growth', 'brand'], s: 'Your week in numbers', m: 'This week: {{week_amount}} BDT from {{week_count}} payments ({{growth}} vs last week).\nTop gateway, busiest day and full breakdown are in reports.', sb: 'সপ্তাহের সারসংক্ষেপ', mb: 'এই সপ্তাহে: {{week_count}} পেমেন্টে {{week_amount}} টাকা (গত সপ্তাহের তুলনায় {{growth}})।\nসেরা গেটওয়ে, ব্যস্ততম দিন ও পূর্ণ বিশ্লেষণ রিপোর্টসে।' },
  { b: 'sys_low_balance', n: 'Device balance low', c: 'SYSTEM', e: 'SYSTEM', v: ['device', 'mfs', 'balance', 'brand'], s: 'Low balance on {{device}} ({{mfs}})', m: 'The {{mfs}} account on {{device}} is down to {{balance}} BDT.\nTop up soon so customer payments keep verifying automatically.', sb: '{{device}}-এ ব্যালেন্স কম ({{mfs}})', mb: '{{device}}-এ {{mfs}} অ্যাকাউন্টে মাত্র {{balance}} টাকা আছে।\nকাস্টমার পেমেন্ট যেন স্বয়ংক্রিয়ভাবে যাচাই হতে পারে সেজন্য দ্রুত রিচার্জ করুন।' },
  { b: 'sys_device_offline', n: 'Device offline', c: 'SYSTEM', e: 'SYSTEM', v: ['device', 'minutes', 'brand'], s: '{{device}} went offline', m: '{{device}} has not checked in for {{minutes}} minutes.\nPayments on that SIM will not auto-verify until it reconnects.\nCheck power, internet and battery optimization on the phone.', sb: '{{device}} অফলাইনে গেছে', mb: '{{minutes}} মিনিট ধরে {{device}} চেক-ইন করেনি।\nপুনরায় সংযোগ না হওয়া পর্যন্ত ওই সিমের পেমেন্ট স্বয়ংক্রিয়ভাবে যাচাই হবে না।\nফোনের পাওয়ার, ইন্টারনেট ও ব্যাটারি অপটিমাইজেশন দেখুন।' },
  { b: 'sys_sms_gateway_error', n: 'SMS gateway error', c: 'SYSTEM', e: 'SYSTEM', v: ['provider', 'error', 'brand'], s: 'SMS gateway issue: {{provider}}', m: 'SMS sending via {{provider}} failed: {{error}}\nFailover chain took over automatically.\nReview credentials in the SMS gateway page.', sb: 'SMS গেটওয়ে সমস্যা: {{provider}}', mb: '{{provider}} দিয়ে SMS পাঠানো ব্যর্থ: {{error}}\nফেইলওভার চেইন স্বয়ংক্রিয়ভাবে দায়িত্ব নিয়েছে।\nSMS গেটওয়ে পেজে ক্রেডেনশিয়াল দেখে নিন।' },
  { b: 'sys_monthly_statement', n: 'Monthly merchant statement', c: 'SYSTEM', e: 'DIGEST', v: ['period', 'gross', 'fees', 'refunds', 'net', 'brand'], s: 'Monthly statement — {{period}}', m: 'Gross: {{gross}} BDT\nFees: {{fees}} BDT\nRefunds: {{refunds}} BDT\nNet: {{net}} BDT\nFull PDF with tax/VAT fields is in Reports → Statements.', sb: 'মাসিক স্টেটমেন্ট — {{period}}', mb: 'মোট: {{gross}} টাকা\nফি: {{fees}} টাকা\nরিফান্ড: {{refunds}} টাকা\nনিট: {{net}} টাকা\nট্যাক্স/ভ্যাট ফিল্ডসহ পূর্ণ PDF রিপোর্টস → স্টেটমেন্ট-এ।' },
  { b: 'sys_incident_alert', n: 'Incident alert', c: 'SYSTEM', e: 'SYSTEM', v: ['title', 'status', 'brand'], s: 'Ongoing incident: {{title}}', m: 'We are working on: {{title}}\nCurrent status: {{status}}.\nLive updates are on the public status page.', sb: 'চলমান ঘটনা: {{title}}', mb: 'আমরা কাজ করছি: {{title}}\nবর্তমান অবস্থা: {{status}}।\nপাবলিক স্টেটাস পেজে লাইভ আপডেট আছে।' },
  // ── OTP (4) ──
  { b: 'otp_6digit', n: 'OTP code (6 digit)', c: 'OTP', e: 'OTP', v: ['code', 'brand'], s: 'Your verification code: {{code}}', m: 'Your one-time code is {{code}}.\nIt expires in 5 minutes and works only once.\nNever share it — nobody from {{brand}} will ever ask for this code.', sb: 'আপনার যাচাইকরণ কোড: {{code}}', mb: 'আপনার এককালীন কোড: {{code}}।\n৫ মিনিটে মেয়াদ শেষ, একবারই কাজ করে।\nকাউকে দেবেন না — {{brand}}-এর কেউ কখনো কোড চাইবে না।' },
  { b: 'otp_4digit', n: 'OTP code (4 digit)', c: 'OTP', e: 'OTP', v: ['code', 'brand'], s: 'Code: {{code}}', m: 'Enter this code to continue: {{code}}\nValid for 5 minutes.', sb: 'কোড: {{code}}', mb: 'চালিয়ে যেতে এই কোড দিন: {{code}}\n৫ মিনিট বৈধ।' },
  { b: 'otp_login', n: 'Login OTP', c: 'OTP', e: 'OTP', v: ['code', 'device', 'brand'], s: 'Sign-in code: {{code}}', m: 'Use {{code}} to sign in from {{device}}.\nDid not try to sign in? Change your password now.', sb: 'লগইন কোড: {{code}}', mb: '{{device}} থেকে লগইনে {{code}} ব্যবহার করুন।\nলগইন করেননি? এখনই পাসওয়ার্ড বদলান।' },
  { b: 'otp_payment_confirm', n: 'Payment confirmation OTP', c: 'OTP', e: 'OTP', v: ['code', 'amount', 'brand'], s: 'Confirm payment of {{amount}} BDT — {{code}}', m: 'To confirm the payment of {{amount}} BDT enter {{code}}.\nExpires in 5 minutes.', sb: '{{amount}} টাকার পেমেন্ট নিশ্চিত করুন — {{code}}', mb: '{{amount}} টাকার পেমেন্ট নিশ্চিত করতে {{code}} দিন।\n৫ মিনিটে মেয়াদ শেষ।' },
]

const TONES: Array<{ suffix: string; label: string; greet: (n: string) => string; close: (b: string) => string }> = [
  { suffix: '_f', label: 'FORMAL', greet: (n) => `Dear {{customer_name}},`, close: (b) => `Best regards,<br/>The {{brand}} Team` },
  { suffix: '_d', label: 'FRIENDLY', greet: (n) => `Hi {{customer_name}},`, close: (b) => `Cheers,<br/>{{brand}}` },
  { suffix: '_m', label: 'MINIMAL', greet: () => '', close: () => '' },
]

function esc(s: string): string {
  return s
}

function buildHtml(message: string, tone: { greet: (n: string) => string; close: (b: string) => string }, brand = 'Invokeil Pay'): string {
  const paras = esc(message)
    .split('\n')
    .map((line) => (line.trim() ? `<p style="margin:0 0 12px;line-height:1.6">${line.trim()}</p>` : ''))
    .join('')
  const greet = tone.greet('')
  const close = tone.close(brand)
  return `<div style="font-family:Arial,Helvetica,sans-serif;max-width:560px;margin:0 auto;color:#0f172a">
<div style="background:#2563EB;color:#fff;padding:20px 24px;border-radius:12px 12px 0 0;font-size:18px;font-weight:700">{{brand}}</div>
<div style="padding:24px;border:1px solid #e2e8f0;border-top:0;border-radius:0 0 12px 12px;font-size:14px">
${greet ? `<p style="margin:0 0 12px;font-weight:600">${greet}</p>` : ''}
${paras}
${close ? `<p style="margin:16px 0 0;color:#64748b">${close}</p>` : ''}
</div>
<div style="padding:12px 4px;color:#94a3b8;font-size:11px;text-align:center">This is an automated message from {{brand}}. Manage notification preferences in your portal.</div>
</div>`
}

export interface CatalogTemplate {
  key: string
  name: string
  category: string
  event: string
  locale: string
  tone: string
  subject: string
  bodyHtml: string
  variables: string[]
}

/** Generate the full catalog: 80 cores × 3 tones (EN) + 80 Bengali (formal) = 320 templates. */
export function generateEmailCatalog(): CatalogTemplate[] {
  const out: CatalogTemplate[] = []
  for (const core of CATALOG_CORES) {
    for (const tone of TONES) {
      out.push({
        key: `${core.b}${tone.suffix}`,
        name: `${core.n} — ${tone.label.toLowerCase()}`,
        category: core.c,
        event: core.e,
        locale: 'en',
        tone: tone.label,
        subject: core.s,
        bodyHtml: buildHtml(core.m, tone),
        variables: core.v,
      })
    }
    // Bengali — formal tone (brand-localized communication for Bangladeshi customers)
    out.push({
      key: `${core.b}_bn`,
      name: `${core.n} — বাংলা`,
      category: core.c,
      event: core.e,
      locale: 'bn',
      tone: 'FORMAL',
      subject: core.sb,
      bodyHtml: buildHtml(core.mb, TONES[0]),
      variables: core.v,
    })
  }
  return out
}

export const CATALOG_COUNT = generateEmailCatalog().length
